export const Resultcontent = [
  {
    id: 0,
    rating: "4.5",
    img: "./adombi.jpg",
    title: "Adombi Hostel",
    type: "This hostel is",
    location: "Ayeduase,North Side",
    host: "Stephen Darkwah",
    amenities: "Wifi · Air condition · kitchen",
    smalldescription: "one in one ,two in one, three in one, four in one",
    price: "(GHS 7K/year),to (GHS 5k/year)",
    roomImages1: "./adombi.jpg",
    roomImages2: "./adombi.jpg",
    description:
      "WhatsApp - ",
  },
  {
    id: 1,
    img: "./paradise.webp",
    rating: "4.0",
    title: " Paradise regained hostel.",
    type: "Paradise is",
    location: "Ayeduase, North-Side",
    host: "Michael Obeng",
    amenities: "Wifi · Washer · kitchen",
    smalldescription: "one in one ,two in one, three in one, four in one",
    price: "ranges from(GHS 8K/year),to (GHS 5k/year)",
    roomImages1: "./adombi.jpg",
    roomImages2: "./adombi.jpg",
    description:
      ". Green Storey-Building Opposite Casa Mara.",
  },
  {
    id: 2,
    img: "./thersah.jpg",
    rating: "4.7",
    title: "St Theresahs Hostel",
    type: "St Theresahs is",
    location: "Ayeduase,north-side",
    host: "Theresah Akomeah",
    amenities: "Wifi · Washer · kitchen",
    smalldescription: "one in one ,two in one, three in one, four in one",
    price: "ranges from (GHS 10K/year),to (GHS 6k/year)",
    roomImages1: "./adombi.jpg",
    roomImages2: "./adombi.jpg",
    description:
      "cream and yellow color building opposite paradise regained.",
  },
  {
    id: 3,
    img: "./p3.jpg",
    rating: "3.7",
    title: "P3 hostel",
    type: "This hostel",
    location: "Ayeduase, North-Side",
    host: "Godwin Boakye Antwi",
    amenities: "Wifi · Washer · iron",
    smalldescription: "two in one, three in one, four in one",
    price: "ranges from (GHS 5K/year),to (GHS 3k/year)",
    roomImages1: "./adombi.jpg",
    roomImages2: "./adombi.jpg",
    description:
      "pink colored hostel Close To Frontline And Opposite Happy Family.",
  },
  {
    id: 4,
    img: "./franco.jpg",
    rating: "3.9",
    title: "Franco Hostel ",
    type: "Franco Hostel is  ",
    location: "North Ayeduase",
    host: "Frank Owusu Ansah",
    amenities: "Wifi · Washer · kitchen",
    smalldescription: "one in one ,two in one, three in one, four in one",
    price: "ranges from (GHS 7K/year),to (GHS 5k/year)",
    roomImages1: "./adombi.jpg",
    roomImages2: "./adombi.jpg",
    description:
      "Pink hostel.",
  },
  {
    id: 5,
    img: "./amandah_hostel.jpg",
    rating: "3.5",
    title: "Amandah Hostel",
    type: "Amandah Hostel is",
    location: "Ayeduase",
    host: "Emmanuel Manasseh",
    amenities: "Wifi · Washer · kitchen",
    smalldescription: "one in one ,two in one, three in one, four in one",
    price: "ranges from (GHS 6K/year),to (GHS 4k/year)",
    roomImages1: "./adombi.jpg",
    roomImages2: "./adombi.jpg",
    description:
      ".Wine story building",
  },
  {
    id: 6,
    img: "./Anarosa.jpg",
    rating: "4.2",
    title: "Anarosa hostel",
    type: "Anarosa hostel",
    location: "Kotei",
    host: "Rosemary Annane",
    amenities: "Wifi · Washer · kitchen",
    smalldescription: "one in one ,two in one, three in one, four in one",
    price: "ranges from GHS4000 to GHS7000",
    roomImages1: "./adombi.jpg",
    roomImages2: "./adombi.jpg",
    description:
      "White Hostel"
  },
  {
    id: 7,
    img: "./canam-hall-2.jpg",
    rating: "3.3",
    title: "Cnam-Hall ",
    type: "Canam-Hall",
    location: "Kotei",
    host: "Augustine Oduro",
    amenities: "Wifi · Washer · iron",
    smalldescription: " 4 in 1, 3 in 1, 2 in 1 ,1 in 1 rooms available",
    price: "ranges from GHS5000 to GHS7000",
    roomImages1: "./adombi.jpg",
    roomImages2: "./adombi.jpg",
    description:
      "A Storey Building Painted with Blue.",
  },
  {
    id: 8,
    img: "./frontline.jpg",
    rating: "3.1",
    title: "Frontline",
    type: "Frontline Hostel",
    location: "Ayeduase ",
    host: "Adams Adomako Baryeh",
    amenities: "Wifi · Washer · iron",
    smalldescription: "4 in 1, 3 in 1, 2 in 1 ,1 in 1 rooms available",
    price: "ranges from GHS4500 to GHS7000",
    roomImages1: "./adombi.jpg",
    roomImages2: "./adombi.jpg",
    description:
      "Painted cream,and close to Shalom Kibutz Hostel"
  },
  {
    id: 9,
    img: "./hydes.jpg",
    rating: "4",
    title: "Hydes Hostel",
    type: "hotel Room",
    location: "Kotei",
    host: "Akpabil Desmond",
    amenities: "Wifi · Washer · iron",
    smalldescription: "4 in 1, 3 in 1, 2 in 1 , rooms available",
    price: "ranges from GHS5000 to GHS7000",
    roomImages1: "./adombi.jpg",
    roomImages2: "./adombi.jpg",
    description:
      "Dark Green and Cream Colour Close to Kotei main road.",
  },
  {
  id:10,
    img: "./dr nap.webp",
    rating: "4.1",
    title: "Dr Nap Apartment",
    type: "Dr Nap Apartment",
    location: "Ayeduase newsite",
    host: "Micheal Ansah",
    amenities: "Wifi · Washer · iron",
    smalldescription: "two in one ,one in one rooms available with shared halls and kitchen",
    price: "ranges from GHS4500 to GHS7000",
    roomImages1: "./adombi.jpg",
    roomImages2: "./adombi.jpg",
    description:
      "deep cream and orange building."
  },
  {
    id:11,
      img: "./jecado.jpg",
      rating: "3.5",
      title: "Jecado Hostel",
      type: "Jecado Hostel",
      location: "Kotei",
      host: "Bismark Oppong",
      amenities: "Wifi · Washer · iron",
      smalldescription: "4 in 1, 3 in 1, 2 in 1 ,1 in 1 rooms available",
      price: "ranges from GHS5000 to GHS7000",
      roomImages1: "./adombi.jpg",
    roomImages2: "./adombi.jpg",
      description:
        "Yellow Building."
    },
    {
      id:12,
        img: "./mass-hostel.jpeg",
        rating: "3.6",
        title: "Mass Hostel",
        type: "Mass Hostel",
        location: "Kotei",
        host: "Micheal Asiedu Sasu",
        amenities: "Wifi · Washer · iron",
        smalldescription: "4 in 1, 3 in 1, 2 in 1 ,1 in 1 rooms available",
        price: "ranges from GHS5000 to GHS6500",
        roomImages1: "./adombi.jpg",
    roomImages2: "./adombi.jpg",
        description:
          "Ash Color with a green roofing."
      },
      {
        id:13,
          img: "./shep 2.jpg",
          rating: "4",
          title: "Sherphed Ville Hostel",
          type: "Sherphed Hostel",
          location: "Kotei",
          host: "Richmond Adu Sarpong",
          amenities: "Wifi · Washer · iron",
          smalldescription: "3 in 1, 2 in 1 ,1 in 1 rooms available",
          price: "ranges from GHS5000 to GHS7500",
          roomImages1: "./adombi.jpg",
    roomImages2: "./adombi.jpg",
          description:
            "Yellowish Colour."
        },
        {
          id:14,
            img: "./no-weapon.jpg",
            rating: "2.9",
            title: "No weapon Annex",
            type: "No weapon Annex",
            location: "Kotei",
            host: "Joseph Opoku Siaw",
            amenities: "Wifi · Washer · iron",
            smalldescription: "4 in 1, 3 in 1, 2 in 1 ,1 in 1 rooms available",
            price: "ranges from GHS4500 to GHS6000",
            roomImages1: "./adombi.jpg",
    roomImages2: "./adombi.jpg",
            description:
              "Three-storey building with a shade of brown."
          },
          {
             id:15,
              img: "./orange hostel.jpg",
              rating: "3",
              title: "Orange Hostel",
              type: "Orange Hostel",
              location: "Kotei",
              host: "Anthony Boateng",
              amenities: "Wifi · Washer · iron",
              smalldescription: "4 in 1, 3 in 1, 2 in 1 ,1 in 1 rooms available",
              price: "ranges from GHS5000 to GHS7000",
              roomImages1: "./adombi.jpg",
    roomImages2: "./adombi.jpg",
              description:
                "A storey building painted in orange ."
            }
        
           ,{ 
              id: 16,
              img: "./wagyingo.jpg",
              rating: "3.8",
              title: "Wagyingo Hostel ",
              type: "Wagyingo Hostel",
              location: "Ayeduase North",
              host: "Emmanuel Amankwah",
              amenities: "Wifi · Washer · iron",
              smalldescription: " 4 in 1, 3 in 1, 2 in 1 ,1 in 1 rooms available",
              price: "ranges from GHS6000 to GHS7000",
              roomImages1: "./adombi.jpg",
    roomImages2: "./adombi.jpg",
              description:
                "Orange and cream structure around FORD Hostel.",
            }      
            ,{ 
              id: 17,
              img: "./wagyingo.jpg",
              rating: "3.8",
              title: "Wagyingo Hostel ",
              type: "Wagyingo Hostel",
              location: "Ayeduase North",
              host: "Emmanuel Amankwah",
              amenities: "Wifi · Washer · iron",
              smalldescription: " 4 in 1, 3 in 1, 2 in 1 ,1 in 1 rooms available",
              price: "ranges from GHS6000 to GHS7000",
              roomImages1: "./adombi.jpg",
    roomImages2: "./adombi.jpg",
              description:
                "Orange and cream structure around FORD Hostel.",
            }      
];

export const Content = [
  {
    id: 0,
    img: "./Adombi.jpg",
    styles: "bigcontents__list1",
    title: "Adombi Hostel",
    price: "GHS 7K/year", 
    description: "Your one stop location to relax and chill in this school year",
  },
  {
    id: 1,
    img: "./paradise.webp",
    styles: "bigcontents__list1",
    title: "Paradise Regained",
    price: "GHS 6K/year",
    description: "Highly Recommended Hostel.",
  },
  {
    id: 5,
    img: "./thersah.jpg",
    styles: "bigcontents__list",
    title: "St.Theresah",
    price: "GHS 8K/year",
    description:
      "Best Security system",
  },
  {
    id: 3,
    img: "./p3.jpg",
    title: "P3",
    price: "GHS 3K/year",
    description: "look no further",
  },
];
